services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-slap
    user: "$UID:$GID"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-slap
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - mysql-exporter
  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter-slap
    ports:
      - "9104:9104"
    volumes:
      - ./mysql-exporter.cnf:/.my.cnf
      - /var/lib/mysql/mysql.sock:/home/mysql.sock
    restart: unless-stopped
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql-slap
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=myuser
    ports:
      - "3306:3306"